export { default as Edit } from './Edit.vue'
export { default as ShopDetails } from './ShopDetails.vue'
export { default as ShopForm } from './ShopForm.vue'
export { default as ShopSidebar } from './ShopSidebar.vue'
export { default as ShopTable } from './ShopTable.vue'
